server:
  port:
    8082
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/mydb?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: rootpwd
  data:
    rest:
      base-path: /api
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${KEYCLOCK_HOST:localhost}:${KEYCLOCK_PORT:8080}/realms/${KEYCLOCK_REALM:local_realm}
      client:
        provider:
          keyclock:
            issuer-uri: http://${KEYCLOCK_HOST:localhost}:${KEYCLOCK_PORT:8080}/realms/${KEYCLOCK_REALM:local_realm}
        registration:
          keyclock:
            authorization-grant-type: authorization_code
            scope: [openid, profile, email]
            client-id: local_client
logging:
  level:
#    root: DEBUG
    org.springframework.web: INFO
    org.hibernate: ERROR
    com.ayshu.gct.spring.aop: DEBUG
    
