server:
  port:
    8084
spring:
  data:
    rest:
      base-path: /api
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: root
    password: rootpwd
    driver-class-name: com.mysql.cj.jdbc.Driver
